# @name signupUser1 
POST http://127.0.0.1:3000/auth/signup
Content-Type: application/x-www-form-urlencoded

username=steve
&password=Argentina!

###

# @name signupUser2 
POST http://127.0.0.1:3000/auth/signup
Content-Type: application/x-www-form-urlencoded

username=cate
&password=Panama1!

###

# @name loginUser1
POST http://127.0.0.1:3000/auth/login
Content-Type: application/x-www-form-urlencoded

username=steve
&password=Argentina!

###

@accessToken1 = {{loginUser1.response.body.accessToken}}

###

# @name loginUser2
POST http://127.0.0.1:3000/auth/login
Content-Type: application/x-www-form-urlencoded

username=cate
&password=Panama1!

###

@accessToken2 = {{loginUser2.response.body.accessToken}}

###

# @name createTask User1 
POST http://127.0.0.1:3000/tasks
Authorization: Bearer {{accessToken1}}
Content-Type: application/x-www-form-urlencoded

title=Something to do
&description=feed the cats

###

# @name createTask User2 
POST http://127.0.0.1:3000/tasks
Authorization: Bearer {{accessToken2}}
Content-Type: application/x-www-form-urlencoded

title=TODO
&description=feed the dogs

###
@id = {{createTask.response.body.id}}

### 

GET http://127.0.0.1:3000/tasks
Authorization: Bearer {{accessToken1}}

### 

GET http://127.0.0.1:3000/tasks
Authorization: Bearer {{accessToken2}}

###

GET http://127.0.0.1:3000/tasks/{{id}}
Authorization: Bearer {{accessToken1}}

###

PATCH http://127.0.0.1:3000/tasks/{{id}}/status
Authorization: Bearer {{accessToken}}
Content-Type: application/x-www-form-urlencoded

status=IN_PROGRESS

###

DELETE http://127.0.0.1:3000/tasks/{{id}}
Authorization: Bearer {{accessToken}}

###
