GET http://127.0.0.1:3000/tasks?search=s
###

# @name createTask 
POST http://127.0.0.1:3000/tasks
Content-Type: application/x-www-form-urlencoded

title=steve
&description=oof!!

###

@id = {{createTask.response.body.id}}

###

GET http://127.0.0.1:3000/tasks/{{id}}

###

PATCH http://127.0.0.1:3000/tasks/{{id}}/status
Content-Type: application/x-www-form-urlencoded

status=IN_PROGRESS

###

DELETE http://127.0.0.1:3000/tasks/{{id}}

###

DELETE http://127.0.0.1:3000/tasks/07ac6034-4441-4abd-acda-34877643ea48